nest/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include,path
from authnest.views00 import home
from django.conf.urls.static import static


admin.AdminSite.site_header = "NEST Administrations"
admin. AdminSite.site_title = "NEST Site Admin"

urlpatterns = [
    path('', home),
    path('admin/', admin.site.urls),
    path('auth/', include('authnest.urls00')),
    path('purchasing/', include('purchasing.urls00')),
    path('purchasing-v1/', include('purchasing.urls01')),
]

if settings.DEBUG:
    # import debug_toolbar
    urlpatterns = [
        # path('gebug/', include(debug_toolbar.urls)),
        path('home/', home),
        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

purchasing/models.py
import datetime
from django.db import models
from django.dispatch import receiver
from django.utils.deconstruct import deconstructible
from django.core.validators import MaxValueValidator
from django.utils import timezone

CH_NEGARA_ASAL = (
    ('US','US'),
    ('UK','UK'),
    ('SG','SG'),
    ('ID','ID'),
    ('AU','AU'),
    ('CA','CA'),
    ('UA','UA'),
    ('GM','GM'),
    ('MY','MY'),
    ('JP','JP'),
    ('PH','PH'),
    ('DK','DK'),
    ('IR','IR'),
    ('ES','ES'),
    ('SE','SE'),
    ('HK','HK'),
)

class IVR7020H(models.Model):
    master = models.CharField(max_length=8)
    po = models.CharField(max_length=25)
    created = models.DateField(null=True,blank=True)
    byr = models.CharField(max_length=3)
    s1 = models.CharField(max_length=1)
    sandi = models.CharField(max_length=4)
    pg = models.CharField(max_length=2)
    f1 = models.CharField(max_length=1)
    p1 = models.CharField(max_length=1)
    c1 = models.CharField(max_length=1)
    pt = models.CharField(max_length=1)
    pi = models.CharField(max_length=3)
    pjk = models.CharField(max_length=3)
    itm = models.PositiveIntegerField()
    pr = models.CharField(max_length=8)
    wom = models.CharField(max_length=6)
    sandi = models.CharField(max_length=4)
    partnumber = models.CharField(max_length=25)
    description = models.CharField(max_length=25)
    duedate = models.DateField(null=True,blank=True)
    qty = models.FloatField()
    um = models.CharField(max_length=2)
    mtu = models.CharField(max_length=3)
    unitprice = models.FloatField()
    extpricerph = models.FloatField()
    vendor = models.CharField(max_length=6)
    vendorname = models.CharField(max_length=25)
    f2 = models.CharField(max_length=2)
    so = models.CharField(max_length=2)
    sr = models.CharField(max_length=2)
    # text = models.CharField(max_length=255)
    hs = models.CharField(max_length=15)
    received = models.DateField(null=True,blank=True)
    inspected = models.DateField(null=True,blank=True)
    stored = models.DateField(null=True,blank=True)
    posts3 = models.DateField(null=True,blank=True)
    c2 = models.CharField(max_length=1)
    p2 = models.CharField(max_length=1)
    dokument = models.CharField(max_length=20)
    engdisp = models.CharField(max_length=20)
    lifetime = models.CharField(max_length=25)
    country = models.CharField(max_length=25)

    class Meta:
        unique_together = [
            ['master', 'itm']
        ]

class TMIN71(models.Model):
    d_create = models.DateField(null=True,blank=True)
    c_nik = models.CharField(max_length=6,blank=True)
    d_appr = models.DateField(null=True,blank=True)
    c_nikappr = models.CharField(max_length=6,blank=True)
    c_po = models.CharField(max_length=8,blank=True)
    d_received = models.DateField(null=True,blank=True)
    b_isclosedr = models.BooleanField(default=False,blank=True)
    c_invoice = models.CharField(max_length=20,blank=True)
    c_packinglist = models.CharField(max_length=20,blank=True)
    c_boxno = models.CharField(max_length=10,blank=True)
    e_certificate = models.CharField(max_length=8,blank=True)
    e_other = models.CharField(max_length=29,blank=True)
    c_negaraasal = models.CharField(max_length=2,choices=CH_NEGARA_ASAL,blank=True)
    c_awb = models.CharField(max_length=20,blank=True)
    d_awb = models.DateField(null=True,blank=True)
    c_hawb = models.CharField(max_length=12,blank=True)
    d_hawb = models.DateField(null=True,blank=True)
    c_bc23 = models.CharField(max_length=20,blank=True)
    d_bc23 = models.DateField(null=True,blank=True)
    c_aju = models.CharField(max_length=26,blank=True)
    d_aju = models.DateField(null=True,blank=True)

    def __str__(self):
        return self.c_po+"-"+self.d_received.strftime("%d %m %y")

    class Meta:
        unique_together = [
            ['c_po', 'd_received']
        ]
        permissions = (
            ('approve_tmin71','Can Approve TMIN71'),
            ('print_tmin71','Can Print TMIN71'),
        )
        ordering = ['-c_po','-d_create','-d_received']

class TMIN72(models.Model):
    d_create = models.DateField(null=True,blank=True)
    f_in71 = models.ForeignKey(TMIN71, on_delete=models.CASCADE)
    c_nik = models.CharField(max_length=6,blank=True)
    d_appr = models.DateField(null=True,blank=True)
    c_nikappr = models.CharField(max_length=6,blank=True)
    i_itemno = models.PositiveIntegerField(blank=True)
    i_qreceived = models.FloatField(blank=True)
    i_qship = models.FloatField(blank=True)
    n_um = models.CharField(max_length=2,blank=True)
    c_partnumber = models.CharField(max_length=20,blank=True)
    c_partin = models.CharField(max_length=20,blank=True)
    c_asterik = models.CharField(max_length=1,blank=True)

    def __str__(self):
        return "ITEM %s - %s : %s %s"%(self.i_itemno,self.c_partnumber,self.i_qship,self.n_um)

    class Meta:
        unique_together = [
            ['f_in71', 'i_itemno']
        ]
        permissions = (
            ('approve_tmin72','Can Approve TMIN72'),
        )
CH_CERT = (
    ('1','1 - Manual / Brocure'),('2','2 - Cert of Warranty'),
    ('3','3 - Engine Document'),('4','4 - Cert of Calibration'),
    ('5','5 - Cert of Origin'),('6','6 - Cert of Test / T Rep'),
    ('7','7 - Cert of Comformance'),('8','8 - Cert of Analys'),
    ('9','9 - Cert of Airworthines'),('A','A - Cert of Mech Char'),
    ('B','B - Form FAA 8130-4'),('C','C - Form FAA 8130-3'),
    ('D','D - EASA Form 1'),('E','E - Form FAA 8130-3 & DAAO 21-18'),
    ('F','F - EASA Form 1 & DAAO 21-18'),('G','G - TCCA 24-0078'),
    ('H','H - Dual EASA Form 1 & FAA 8130-3'),('I','I - DAAO 21-18'),
    ('J','J - Hydrostatic Test Result'),('K','K - Burst Test Result'),
    ('L','L - ECER110 & OR ISO 11439'),('M','M - Cert of Material'),
    ('N','N - IDS (Inspection Data Sheet)'),
    ('O','O - DUAL (FAA 8130-3 & EASA F1 or FAA 8130-3 Only'),
    ('P','P - DUAL (FAA 8130-3 & EASA F1 or EASA Form Only'),
    ('Q','Q - FAA 8130-3 or EASA Form 1'),('R','R - Ok for Assy'),
)
CH_ELIGIBILITY = (
    ('1','1 - DGCA'),('2','2 - FAA'),('3','3 - EASA'),('4','4 - FAA & EASA'),
    ('5','5 - DGCA & FAA'),('6','6 - DGCA & EASA'),('7','7 - ALL AUTHORITY'),
    ('8','8 - N/A'),
)
CH_COND = (
    ('0','0 - Unserviceable'),('1','1 - New'),('2','2 - Farm Out'),
    ('3','3 - Repair In House'),('4','4 - OHC'),('5','5 - Serviceable'),
    ('6','6 - Repairable for Trading'),('7','7 - Repair / Modified'),
    ('8','8 - Inspected / New'),('9','9 - Inspected / As Remove'),
    (' ','  - Unserviceable'),
)
class TMIN73(models.Model):
    d_create = models.DateField(null=True,blank=True)
    f_in72 = models.OneToOneField(TMIN72, on_delete=models.CASCADE)
    c_nik = models.CharField(max_length=6,blank=True)
    c_asterik = models.CharField(max_length=1,blank=True)
    i_qacc = models.FloatField(null=True,blank=True)
    c_cert = models.CharField(max_length=1,choices=CH_CERT)
    c_e = models.CharField(max_length=1,choices=CH_ELIGIBILITY)
    c_cond = models.CharField(max_length=1,choices=CH_COND)

    def __str__(self):
        return "ITEM %s - %s : %s %s"%(self.f_in72.i_itemno,self.f_in72.c_partnumber,self.i_qacc,self.f_in72.n_um)

    class Meta:
        permissions = (
            ('approve_tmin73','Can Approve TMIN73'),
        )

class TMIN75(models.Model):
    d_create = models.DateField(null=True,blank=True)
    f_in73 = models.OneToOneField(TMIN73, on_delete=models.CASCADE)
    c_nik = models.CharField(max_length=6,blank=True)
    c_ciridap = models.CharField(max_length=10,blank=True)
    c_owner = models.CharField(max_length=3)
    c_bin = models.CharField(max_length=10)
    c_recvno = models.PositiveIntegerField(validators=[MaxValueValidator(99999)])

    def __str__(self):
        return "V"+self.d_create.strftime("%y")+str(self.c_recvno).zfill(5)


class TMIN76(models.Model):
    d_release = models.DateField()
    f_in73 = models.OneToOneField(TMIN73, on_delete=models.CASCADE)
    c_nik = models.CharField(max_length=6,blank=True)
    i_qreject = models.FloatField(null=True,blank=True)
    c_npo = models.CharField(max_length=1,blank=True)
    c_drno = models.PositiveIntegerField(validators=[MaxValueValidator(9999)])
    c_sts = models.PositiveIntegerField(validators=[MaxValueValidator(9)])

    def __str__(self):
        return "D"+self.d_release.strftime("%y")+str(self.c_npo)+str(self.c_drno).zfill(4)

purchasing/templates/purchasing/f_in71.html
{% extends 'ui/base.html' %}
{% load static %}
{% block content %}
<div class="container content">

  <form class="form-mf" method="post">
    {% csrf_token %}
    <div class="pure-g" style="background-color:black">
      <div class="pure-u-2-3">
        <div class="form-mf-body py-2">
          <pre> IN71               PACKING-LIST RECORDING</pre>
          <pre> </pre>
          <pre> {{ form.func.label }}: {{ form.func }} (A-ADD C-CHNG I-INQ P-PRINT R-APPROVE)</pre>
          <pre> </pre>
          <pre> {{ form.c_po.label }}      : {{ form.c_po }}                                            </pre>
          <pre> {{ form.d_received.label }}: {{ form.d_received }}  {{ form.b_isclosedr.label }}: {{ form.b_isclosedr }}  CREATE: {{ instance.d_create|date:"dby"|default:"       " }}  APPR: {{ instance.c_nikappr }} </pre>
          <pre> </pre>
          <pre> {{ form.c_invoice.label }}     : {{ form.c_invoice }}</pre>
          <pre> {{ form.c_packinglist.label }}: {{ form.c_packinglist }}</pre>
          <pre> {{ form.c_boxno.label }}       : {{ form.c_boxno }}</pre>
          <pre> {{ form.e_certificate.label }}  : {{ form.e_certificate }}  {{ form.e_other.label }}: {{ form.e_other }}</pre>
          <pre> {{ form.c_awb.label }}    : {{ form.c_awb }}</pre>
          <pre> {{ form.d_awb.label }}     : {{ form.d_awb }}</pre>
          <pre> {{ form.c_hawb.label }}         : {{ form.c_hawb }}</pre>
          <pre> {{ form.d_hawb.label }}    : {{ form.d_hawb }}</pre>
          <pre> {{ form.c_bc23.label }} : {{ form.c_bc23 }}  {{ form.d_bc23.label }} : {{ form.d_bc23 }}</pre>
          <pre> {{ form.c_negaraasal.label }}  : {{ form.c_negaraasal }}            {{ form.c_aju.label }}: {{ form.c_aju }}</pre>
          <pre>                                      {{ form.d_aju.label }}  : {{ form.d_aju }}</pre>

          </div>
        <div class="form-mf-footer">
          <input class="btn btn-primary ml-2 mb-2" type="submit" name="submit" value="Submit">
          <a href="{% url 'purchasing:in71' %}" class="btn btn-danger mb-2">Reset</a>
        </div>
      </div>
      <div class="pure-u-1-3">
        <div class="form-mf-error pl-3">
          {% include "ui/alert_form-mf.html" %}
          {{ form.non_field_errors|safe }}
          {% for field in form %}
            {% if field.errors %}
              {{ field.errors|safe }} <strong>{{ field.label_tag }}</strong><br>
            {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}
{% block script %}
{{ block.super }}
<script>

function ChangeFunc(act){
  var dischg = 'dischg';
  if (act == 'change' | act == 'approve' | act == 'print' ){
    $('#id_c_po').addClass(dischg);
    $('#id_c_po').attr('readonly','readonly');
    $('#id_d_received').addClass(dischg);
    $('#id_d_received').attr('readonly','readonly');
    // $('#id_d_received').removeClass('hasDatepicker');
    // $('#id_d_received').removeClass('dateinput-dmy');
  }else{
    $('#id_c_po').removeClass(dischg);
    $('#id_c_po').removeAttr('readonly');
    $('#id_d_received').removeClass(dischg);
    $('#id_d_received').removeAttr('readonly');
    // $('#id_d_received').addClass('hasDatepicker');
    // $('#id_d_received').addClass('dateinput-dmy');
  }
}
$('#field-func').change(function(){
  var act = $(this).val();
  ChangeFunc(act)
});
$(document).ready(function(){
  var act = $('#field-func').val();
  ChangeFunc(act)
});
</script>

{% endblock %}

purchasing/templates/purchasing/f_in71_print.html
{% extends 'ui/base.html' %}
{% load static %}
{% block content %}
<style>
  @media print {
		body * { visibility: hidden; }
    #printarea { visibility: visible; }
		#printarea * { visibility: visible; }
		@page {
		  size: 9.5in 3.5in;
      margin: 0;
		}
	}
</style>
<div class="container content">
  <div class="row justify-content-center">
    <div class="col">
      <div class="card">
        <div class="card-header">
          <a href="/purchasing/in71" class="btn btn-primary"><i class="fa fa-chevron-left"></i> Back</a>
          <button class="btn btn-primary"><i class="fa fa-print"></i> Print</button>
        </div>
        <div class="card-body">
          <div id="printarea">
            {{ obj }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block script %}
{{ block.super }}
{% endblock %}

purchasing/templates/purchasing/f_in72.html
{% extends 'ui/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
<div class="container content">

  <form class="form-mf" method="post">
    {% csrf_token %}
    <div class="pure-g" style="background-color:black">
      <div class="pure-u-2-3">
        <div class="form-mf-body py-2">
<pre> IN72               QUANTITY-RECEIVING-INSPECTION                               </pre>
<pre>                                                                                </pre>
<pre>                                                                                </pre>
<pre> {{ in71_form.func.label }}: {{ in71_form.func }} (A-ADD I-INQ R-APPROVE)                                            </pre>
<pre>                                                                                </pre>
<pre> {{ in71_form.c_po.label }}: {{ in71_form.c_po }}                   PACKING#: {{ in71_form.instance.c_packinglist}}                               </pre>
<pre> {{ in71_form.d_received.label }}: {{ in71_form.d_received }} CREATED: {{ in71_form.instance.d_create|date:"dby"|default:"       "}}  INVOICE#: {{ in71_form.instance.c_invoice|ljust:"20"}} </pre>
<pre>                                                                                </pre>
<pre> ITEM# PART#              S/A/C/D  Q-SHIP   UM  Q-RECVD        PART#-IN         </pre>
<pre> ------------------------------------------------------------------------------ </pre>
{{ in72_formset.management_form }}

{% for fs in in72_formset  %}
{% for hidden in fs.hidden_fields  %}
{{hidden}}
{% endfor %}
{% if not forloop.last %}
<div style="display:none">{{ fs.c_asterik}}{{ fs.c_partnumber }}{{ fs.n_um}}</div>
<pre> {{ fs.i_itemno }} {{ fs.c_asterik.value|default:"&nbsp;"|safe}} {{ fs.c_partnumber.value|default_if_none:" "|ljust:"20" }} {{ fs.func_sacd }}  {{ fs.i_qship }}  {{ fs.n_um.value|default_if_none:"" }} {{ fs.i_qreceived }} </pre>
{% endif %}
{% endfor %}






          </div>
        <div class="form-mf-footer">
          <input class="btn btn-primary ml-2 mb-2" type="submit" name="submit" value="Submit">
          <a href="{% url 'purchasing:in72' %}" class="btn btn-danger mb-2">Reset</a>
        </div>
      </div>
      <div class="pure-u-1-3">
        <div class="form-mf-error pl-3">
          {% include "ui/alert_form-mf.html" %}
          {{ form.non_field_errors|safe }}
          {% for field in form %}
            {% if field.errors %}
              {{ field.errors|safe }} <strong>{{ field.label_tag }}</strong><br>
            {% endif %}
          {% endfor %}
          {% for fs in in72_formset  %}
            {{ fs.non_field_errors|safe }}
            {% for field in fs %}
              {% if field.errors %}
                {{ field.errors|safe }} <strong>{{ field.label_tag }}</strong><br>
              {% endif %}
            {% endfor %}
          {% endfor %}
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}
{% block script %}
{{ block.super }}
<script>

function ChangeFunc(act){
  var dischg = 'dischg';
  if (act == 'change' | act == 'approve' | act == 'print' ){
    $('#id_c_po').addClass(dischg);
    $('#id_c_po').attr('readonly','readonly');
    $('#id_d_received').addClass(dischg);
    $('#id_d_received').attr('readonly','readonly');
    // $('#id_d_received').removeClass('hasDatepicker');
    // $('#id_d_received').removeClass('dateinput-dmy');
  }else{
    $('#id_c_po').removeClass(dischg);
    $('#id_c_po').removeAttr('readonly');
    $('#id_d_received').removeClass(dischg);
    $('#id_d_received').removeAttr('readonly');
    // $('#id_d_received').addClass('hasDatepicker');
    // $('#id_d_received').addClass('dateinput-dmy');
  }
}
function pad(num, size) {
    var s = num+"";
    while (s.length < size) s = "0" + s;
    return s;
}

//### Function to add leading zero(s)
$('#field-func').change(function(){
  var act = $(this).val();
  ChangeFunc(act)
});
$(document).ready(function(){
  var act = $('#field-func').val();
  ChangeFunc(act)
  // $('.zeropad').val(pad($(this).val(), $(this).data('zeropad')));
  $('.zeropad').each(function(){
    $(this).val(pad($(this).val(), $(this).data('zeropad')));
  });
});
</script>

{% endblock %}

purchasing/templates/purchasing/f_in73.html
{% extends 'ui/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
<style>
  .field-func{
    width: auto !important;
  }
</style>
<div class="container content">

  <form class="form-mf" method="post">
    {% csrf_token %}
    <div class="pure-g" style="background-color:black">
      <div class="pure-u-2-3">
        <div class="form-mf-body py-2">

<pre> IN73                QUALITY-RECEIVING-INSPECTION           EMPLNO:             </pre>
<pre>                                                            PASSWD:             </pre>
<pre>                                                                               </pre>
<pre> {{ in71_form.func.label }}: {{ in71_form.func }} (A-ADD I-INQ)                                                      </pre>
<pre>                                                                               </pre>
<pre> {{ in71_form.c_po.label }}: {{ in71_form.c_po }}                   PACKING#: {{ in71_form.instance.c_packinglist}}                               </pre>
<pre> {{ in71_form.d_received.label }}: {{ in71_form.d_received }} CREATED: {{ in71_form.instance.d_create|date:"dby"}}  INVOICE#: {{ in71_form.instance.c_invoice|ljust:"20"}} PAGE:</pre>
<pre>                                                                               </pre>
<pre> S ITM   PART#                Q-SHIP   A Q-ACCEPT  C E CON T PART#-IN            </pre>
<pre> -------------------------------------------------------------------------------</pre>
{{ in73_formset.management_form }}
{% for fs in in73_formset  %}
{% for hidden in fs.hidden_fields  %}
{{hidden}}
{% endfor %}
{% if not forloop.last %}
<div style="display:none">{{ fs.c_asterik}}{{ fs.c_partnumber }}{{ fs.n_um}}</div>
  {% with ins=fs.instance %}
    <pre>   {{ ins.f_in72.i_itemno|stringformat:".3d" }} {{ fs.c_asterik.value|default:"&nbsp;"|safe}} {{ ins.f_in72.c_partnumber|default_if_none:" "|ljust:"20" }} {{ ins.f_in72.i_qship|stringformat:".2f"|rjust:"7" }} {{ fs.func_sacd }}{{ fs.i_qacc }} {{ fs.c_cert }} {{ fs.c_e }} {{ fs.c_cond }} </pre>
  {% endwith %}
{% endif %}
{% endfor %}







          </div>
        <div class="form-mf-footer">
          <input class="btn btn-primary ml-2 mb-2" type="submit" name="submit" value="Submit">
          <a href="{% url 'purchasing:in73' %}" class="btn btn-danger mb-2">Reset</a>
        </div>
      </div>
      <div class="pure-u-1-3">
        <div class="form-mf-error pl-3">
          {% include "ui/alert_form-mf.html" %}
          {{ form.non_field_errors|safe }}
          {% for field in form %}
            {% if field.errors %}
              {{ field.errors|safe }} <strong>{{ field.label_tag }}</strong><br>
            {% endif %}
          {% endfor %}
          {% for fs in in73_formset  %}
            {{ fs.non_field_errors|safe }}
            {% for field in fs %}
              {% if field.errors %}
                {{ field.errors|safe }} <strong>{{ field.label_tag }}</strong><br>
              {% endif %}
            {% endfor %}
          {% endfor %}
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}
{% block script %}
{{ block.super }}
<script>

function ChangeFunc(act){
  var dischg = 'dischg';
  if (act == 'change' | act == 'approve' | act == 'print' ){
    $('#id_c_po').addClass(dischg);
    $('#id_c_po').attr('readonly','readonly');
    $('#id_d_received').addClass(dischg);
    $('#id_d_received').attr('readonly','readonly');
    // $('#id_d_received').removeClass('hasDatepicker');
    // $('#id_d_received').removeClass('dateinput-dmy');
  }else{
    $('#id_c_po').removeClass(dischg);
    $('#id_c_po').removeAttr('readonly');
    $('#id_d_received').removeClass(dischg);
    $('#id_d_received').removeAttr('readonly');
    // $('#id_d_received').addClass('hasDatepicker');
    // $('#id_d_received').addClass('dateinput-dmy');
  }
}

//### Function to add leading zero(s)
$('#field-func').change(function(){
  var act = $(this).val();
  ChangeFunc(act)
});
$(document).ready(function(){
  var act = $('#field-func').val();
  ChangeFunc(act)

});
</script>

{% endblock %}

purchasing/templates/purchasing/in71_print.html
{% extends 'ui/base.html' %}
{% load static %}
{% load mathfilters %}
{% block navbar %}

{% endblock %}
{% block content %}
<style>
  /* .table-print td{
    border-top: solid grey 1pt !important;
    border-bottom: solid grey 1pt !important;
  } */
  .table-print th{
    border-top: solid black 1pt !important;
    border-bottom: solid black 1pt !important;
  }
  .table-inside td{
    border:none !important;
  }
</style>
<div class="container" style="width:210mm;">
  <div class="row justify-content-center">
    <div class="col">

          <div id="printarea">
            <table class="table table-sm table-print" >
              <thead>
                <tr>
                  <td colspan="6" class="text-center" style="border:none!important"><b> MATERIAL-RECEIVING-RECORD </b></td>
                </tr>
                <tr>
                  <td colspan="6" style="border:none!important">
                    <table class="table table-sm table-inside">
                      <tr>
                        <td>P.O#</td><td>: {{obj.c_po}}</td><td></td>
                        <td>INVOICE#</td><td>: {{obj.c_invoice}}</td>
                      </tr>
                      <tr>
                        <td>DATE</td><td>: {{obj.d_received|date:"d b y"|upper}}</td><td></td>
                        <td>PACKING-LIST</td><td>: {{obj.c_packinglist}}</td>
                      </tr>
                      <tr>
                        <td>FROM</td><td>: {{ivr.vendor}}</td><td></td>
                        <td>AWB/BL/SJ</td><td>: {{obj.c_awb}}</td>
                      </tr>
                      <tr>
                        <td></td><td> &nbsp; {{ivr.vendorname}}</td><td></td>
                        <td>BOX#</td><td>: {{obj.c_boxno}}</td>
                      </tr>
                    </table>
                  </td>
                </tr>
                <tr>
                  <th style="width:15mm;" class=" text-right">ITEM#</th>
                  <th class="">PART-NUMBER<br>PART-DESCRIPTION</th>
                  <th style="width:10mm;" class=" text-right">CND</th>
                  <th style="width:40mm;" class=" text-right">QUANTITY<br>RECV/ACC/RJECT</th>
                  <th style="width:10mm;" class="">UM</th>
                  <th style="width:40mm;" class="">BIN#<br>R-VCHR#/DR#</th>
                </tr>
              </thead>
              <tbody>
                {% for in72 in obj.tmin72_set.all  %}
                <tr>
                  <td class="text-right">{{in72.i_itemno}}</td>
                  <td>{{in72.c_partnumber}}<br>{{in72.ivr.description}}</td>
                  <td class="text-center">{{in72.tmin73.c_cond}}</td>
                  <td class="text-right">{{in72.i_qreceived}}<br>{{in72.tmin73.i_qacc|default:'0.0'}}<br>{{in72.i_qreceived|sub:in72.tmin73.i_qacc|default:'0.0'}}<br></td>
                  <td>{{in72.n_um}}</td>
                  <td></td>
                </tr>
                {% endfor %}
                <tr>
                  <td colspan="6" style="border:none!important;"><br><br><br>CERT/DOC : N/A<br><br><br><br></td>
                </tr>
                <tr>
                  <td colspan="6" style="border:none!important;">
                    <table class="table table-sm table-inside">
                      <tr>
                        <td class="text-center"><br><br>RECEIVED-BY:<br><br><br><br>(..............................)</td>
                        <td class="text-center"><br><br>INSPECTED-BY:<br><br><br><br>(..............................)</td>
                        <td class="text-center"><br><br>STORED-BY:<br><br><br><br>(..............................)</td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </tbody>

            </table>
          </div>

    </div>
  </div>
</div>
{% endblock %}
{% block script %}
{{ block.super }}
{% endblock %}